"""Fixtures that are used throughout the rse-survey-report."""

NORDICS = ["Finland", "Norway", "Sweden", "Denmark", "Iceland", "Estonia"]

# categories and their question ids, in the order of the parts in rse-book/_quarto.yml
# country-specific ids follow their section in RSE_survey_outline/survey-process.md
CATEGORIES = {
    "Setup": ["startlanguage", "startdate"],
    "RSE role": ["rse1", "rse3", "rse4de"],
    "Education": ["edu2", "edu1"],
    "Software experience": ["soft2can", "soft1can"],
    "Open science": ["open1de", "open1can"],
    "UK RSE network": ["ukrse1", "ukrse3"],
    "RSE Organisation": [
        "org1can",
        "org1cz",
        "org1swiss",
        "ukrse12sa",
        "proj6uk",
        "org2can",
        "org3nord",
        "org3us",
        "org4nord",
        "org4us",
        "org5us",
        "org3de",
        "org4de",
        "org5de",
        "org6de",
        "org7de",
    ],
    "Employment": [
        "currentEmp1",
        "currentEmp1qde",
        "currentEmp1qswiss",
        "currentEmp1nl",
        "currentEmp1qzaf",
        "prevEmp1",
        "prevEmp1qde",
        "prevEmp1nl",
        "prevEmp1qswiss",
        "currentEmp5",
        "currentEmp6",
        "currentEmp60",
        "currentEmp12",
        "currentEmp10",
        "currentEmp11",
        "currentEmp11qcl",
        "currentEmp11qzaf",
        "currentEmp13",
        "currentEmp2q",
        "currentEmp20deqde",
        "currentEmp20qus",
        "currentEmp21deqde",
        "currentEmp22deqde",
        "currentEmp23deqde",
        "currentEmp24deqde",
    ],
    "Likert scales": [
        "likert0",
        "likert1",
        "likert2a",
        "likert2b",
        "likert3a",
        "likert3b",
        "likert4a",
        "likert4b",
        "likert4c",
        "likert5b",
        "likert5a",
    ],
    "Turnover": ["turnOver3", "turnOver3zaf", "turnOver4zaf"],
    "Work activities": [
        "currentWork2",
        "currentWork1",
        "currentWork2qcl",
        "currentWork3nord",
    ],
    "Publications": ["paper3mod", "paper2mod"],
    "Conferences": ["conf1can", "conf2can", "ref1uk"],
    "Project Management": [
        "proj1can",
        "proj8can",
        "proj7can",
        "proj4can",
        "proj5can",
        "proj5zaf",
        "proj6zaf",
    ],
    "Job stability": ["stability1", "stability2"],
    "Training": [
        "train2",
        "train3",
        "train4",
        "train4qzaf",
        "train5",
        "skillNord",
        "skill2",
    ],
    "Funding": ["fund3", "fund3qnl", "fund1nord", "fund1can", "fund1uk"],
    "Tooling": ["tool5", "tool5can", "tool2", "tool4can"],
    "Generative AI": ["genAI1", "genAI2", "genAI3", "genAI4", "genAI5", "genAI6"],
    "Demographics": ["socio3"],
}
