project:
  type: book
  output-dir: _book
book:
  title: "International RSE Survey 2026"
  author: "RSE Survey Team"
  date: today
  site-url: https://nordic-rse.github.io/rse-survey-2026/
  chapters:
    - part: "About"
      chapters:
        - index.qmd
        - about/user-guide.qmd
    - part: "RSE role"
      chapters:
        - chapters/rse1_0.qmd
        - chapters/rse3_0.qmd
        - chapters/rse4de_0.qmd
    - part: "Education"
      chapters:
        - chapters/edu2_0.qmd
        - chapters/edu1_0.qmd
    - part: "Software experience"
      chapters:
        - chapters/soft2can_0.qmd
        - chapters/soft1can_0.qmd
    - part: "Open science"
      chapters:
        - chapters/open1de_0.qmd
        - chapters/open1can.qmd
    - part: "UK RSE network"
      chapters:
        - chapters/ukrse3.qmd
    - part: "Employment"
      chapters:
        - chapters/currentEmp5_0.qmd
        - chapters/currentEmp6_0.qmd
        - chapters/currentEmp60_0.qmd
        - chapters/currentEmp12_0.qmd
        - chapters/currentEmp10_0.qmd
        - chapters/currentEmp11_0.qmd
        - chapters/currentEmp13.qmd
        - chapters/currentEmp2q_0.qmd
    - part: "Likert scales"
      chapters:
        - chapters/likert01.qmd
        - chapters/likert3a.qmd
        - chapters/likert3b.qmd
        - chapters/likert5b.qmd
        - chapters/likert2a.qmd
        - chapters/likert2b.qmd
    - part: "Work activities"
      chapters:
        - chapters/currentWork2_0.qmd
        - chapters/currentWork1_0.qmd
    - part: "Publications"
      chapters:
        - chapters/paper3mod_0.qmd
        - chapters/paper2mod.qmd
    - part: "Conferences"
      chapters:
        - chapters/conf1can_0.qmd
        - chapters/conf2can_0.qmd
    - part: "Project Management"
      chapters:
        - chapters/proj1can_0.qmd
        - chapters/proj8can_0.qmd
        - chapters/proj4can.qmd
        - chapters/proj5zaf.qmd
        - chapters/proj6zaf.qmd
    - part: "Job stability"
      chapters:
        - chapters/stability1_0.qmd
        - chapters/stability2_0.qmd
    - part: "Training"
      chapters:
        - chapters/train2_0.qmd
        - chapters/train3_0.qmd
        - chapters/train4_0.qmd
        - chapters/train5.qmd
        - chapters/skill2.qmd
    - part: "Funding"
      chapters:
        - chapters/fund3.qmd
    - part: "Tooling"
      chapters:
        - chapters/tool5.qmd
        - chapters/tool2.qmd
        - chapters/tool4.qmd
    - part: "Generative AI"
      chapters:
        - chapters/genAI1_0.qmd
        - chapters/genAI2.qmd
        - chapters/genAI3.qmd
        - chapters/genAI4.qmd
        - chapters/genAI5.qmd
        - chapters/genAI6_0.qmd
    - part: "Demographics"
      chapters:
        - chapters/socio3_0.qmd
  appendices:
    - appendices/methodology.qmd
    - appendices/recoding.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    # embed-resources: true
execute:
  dir: project
  freeze: auto
resources:
  - data/
  - _artifacts/**/*.png
  - _artifacts/**/*.md
  - _artifacts/**/*.csv
