project:
  type: book
  output-dir: _book
book:
  title: "International RSE Survey 2026"
  author: "RSE Survey Team"
  date: today
  chapters:
    - index.qmd
    - part: "RSE role"
      chapters:
        - chapters/rse1.qmd
        - chapters/rse3.qmd
        - chapters/rse4de.qmd
    - part: "Education"
      chapters:
        - chapters/edu1.qmd
    - part: "Software experience"
      chapters:
        - chapters/soft2can.qmd
        - chapters/soft1can.qmd
    - part: "Open science"
      chapters:
        - chapters/open1de.qmd
        - chapters/open1can.qmd
    - part: "UK RSE network"
      chapters:
        - chapters/ukrse1.qmd
        - chapters/ukrse3.qmd
    - part: "RSE Organisation"
      chapters:
        - chapters/org1can.qmd
        - chapters/org2can.qmd
        - chapters/org3nord.qmd
        - chapters/org4nord.qmd
    - part: "Employment"
      chapters:
        - chapters/currentEmp1.qmd
        - chapters/prevEmp1.qmd
        - chapters/currentEmp6.qmd
        - chapters/currentEmp12.qmd
        - chapters/currentEmp10.qmd
        - chapters/currentEmp13.qmd
    - part: "Likert scales"
      chapters:
        - chapters/likert0.qmd
        - chapters/likert1.qmd
        - chapters/likert3a.qmd
        - chapters/likert3b.qmd
        - chapters/likert4b.qmd
        - chapters/likert5b_1.qmd
        - chapters/likert5b_2.qmd
        - chapters/likert5b_3.qmd
        - chapters/likert5a_1.qmd
        - chapters/likert5a_2.qmd
        - chapters/likert5a_3.qmd
        - chapters/likert2a.qmd
        - chapters/likert2b.qmd
    - part: "Turnover"
      chapters:
        - chapters/turnOver3.qmd
    - part: "Work activities"
      chapters:
        - chapters/currentWork2.qmd
        - chapters/currentWork1.qmd
        - chapters/currentWork2qcl.qmd
        - chapters/currentWork3nord.qmd
    - part: "Publications"
      chapters:
        - chapters/paper3mod.qmd
        - chapters/paper2mod.qmd
    - part: "Conferences"
      chapters:
        - chapters/conf1can.qmd
    - part: "Project Management"
      chapters:
        - chapters/proj1can.qmd
        - chapters/proj8can.qmd
        - chapters/proj4can.qmd
        - chapters/proj5zaf.qmd
        - chapters/proj6zaf.qmd
    - part: "Job stability"
      chapters:
        - chapters/stability1.qmd
        - chapters/stability2.qmd
    - part: "Training"
      chapters:
        - chapters/train2.qmd
        - chapters/train4.qmd
        - chapters/train5.qmd
        - chapters/skillNord.qmd
    - part: "Funding"
      chapters:
        - chapters/fund3.qmd
        - chapters/fund1nord.qmd
    - part: "Tooling"
      chapters:
        - chapters/tool5.qmd
        - chapters/tool2.qmd
        - chapters/tool4can.qmd
    - part: "Generative AI"
      chapters:
        - chapters/genAI1.qmd
        - chapters/genAI2.qmd
        - chapters/genAI3.qmd
        - chapters/genAI4.qmd
        - chapters/genAI5.qmd
    - part: "Demographics"
      chapters:
        - chapters/socio3.qmd
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
execute:
  echo: false
  warning: false
  freeze: auto
jupyter: python3
